### ISSUE TITLE
MSI installer could user our logo

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust-packaging#15]
Right now I'm looking at a red CD icon, but it'd be cool if we could get the Rust gear in there!

cc @vadimcn

**Comment by vadimcn** [comment]
Unfortunately it isn't just the icon.  You have to replace the whole top panel.

If anybody is feeling artsy, here's a spec of the graphical assets that we'll need: http://wixtoolset.org/documentation/manual/v3/wixui/wixui_customizations.html#replacing-the-default-bitmaps.  We'd probably want to replace both WixUIBannerBmp and WixUIDialogBmp.
