### ISSUE TITLE
MSI weirdness

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust-packaging#40]
For the Visual Rust Toolchain Manager, I'm playing around with the MSI and getting unattended per-user installs to work.

If you want to play along, try something like: `msiexec /i some-rust-installer.msi /quiet /l* log.txt INSTALLDIR=C:\Users\Me\Desktop\RustTmp`

I haven't figured out how to avoid it requesting admin privileges. Maybe http://blogs.msdn.com/b/windows_installer_team/archive/2009/09/02/authoring-a-single-package-for-per-user-or-per-machine-installation-context-in-windows-7.aspx helps?

**Comment by vadimcn** [comment]
Did you try adding MSIINSTALLPERUSER=1 ?

And yes, MSI does not support installing a product more than once (aside from weird corner cases, like two users installing per-user independently)

What's a "toolchain manager"?

**Comment by cmr** [comment]
Multirust-for-Windows, pretty much.

I did try MSIINSTALLPERUSER=1 but it didn't appear to make a difference.

**Comment by cmr** [comment]
I just realized there are tarballs for windows, so I'll just use those, but someone in the future may want to use the MSIs in this way.

**Comment by vadimcn** [comment]
@cmr: so you ran it with the above command line + MSIINSTALLPERUSER=1, and it failed to install?

**Comment by cmr** [comment]
I guess I tried it in combination with other stuff that was broken, it does install like that.

**Comment by cmr** [comment]
Thanks @vadimcn!

**Comment by vadimcn** [comment]
Yeah, a multirust port should be using tarrballs.  Msi is not really designed for that kind of a task.
