### ISSUE TITLE
Fails on non-privileged user account.

### ISSUE THREAD

**Issue by Jexell** [rust-lang/rust-packaging#5]
The previous installer which only installed rust would ask for you to enter a admin password. The new installer which installs both rust and cargo fail instead requiring you to run it as an admin.

**Comment by brson** [comment]
The new installer is derived from the old one and I don't believe it ever requested sudo. That said, it might be a good idea for the installer to ask for root if it determines that it can't install. I filed this against rust-installer https://github.com/rust-lang/rust-installer/issues/7

**Comment by Jexell** [comment]
@brson I should I have also said that I run windows 7.
